config/routes.rb
Rails.application.routes.draw do

  resources :inventories
  namespace :api do
    namespace :v1 do
      resources :basics, :skills
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basic.rb
class Basic < ApplicationRecord
  has_one :skill, dependent: :destroy
  has_one :inventory, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :basic
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :basic
end

app/controllers/api/v1/basics_controller.rb
class Api::V1::BasicsController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_action :set_basic, only: [:show, :edit, :update, :destroy]

  # GET /basics

  def index
    @basics = Basic.all
    render json: @basics
  end

  # GET /basics/1

  def show
    render json: @basic
  end

  # POST /basics

  def create
    @basic = Basic.new(basic_params)
    if @basic.save
      render json: @basic, status: :created, location: api_v1_basic_url(@basic)
    else
      render json: @basic.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /basics/1
  def update

    if @basic.update(basic_params)

      render json: @basic

    else

      render json: @basic.errors, status: :unprocessable_entity
    end
  end

  # DELETE /basics/1

  def destroy
    @basic.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basic
      @basic = Basic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basic_params
      p 'got to params fxn'
      params.require(:basic).permit(:name, :age, :sex, :classs, :race, :height)
    end
end

app/controllers/api/v1/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories

  def index
    @inventories = Inventory.all
    render json: @inventories
  end

  # GET /inventories/1

  def show
    render json: @inventory
  end

  # POST /inventories

  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      @inventory = Basic.new(basic_params)
      if @inventory.save
        render json: @inventory, status: :created, location: api_v1_basic_url(@inventory)
      else
        render json: @inventory.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /inventories/1

  def update

        if @inventory.update(basic_params)

          render json: @inventory

        else

          render json: @inven.errors, status: :unprocessable_entity
        end

  end

  # DELETE /inventories/1

  def destroy
    @inventory.destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:id, :name)
    end
end

app/controllers/api/v1/skills_controller.rb
class Api::V1::SkillsController < ApplicationController

  skip_before_action :verify_authenticity_token
  
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills

  def index
    @skills = Skill.all
    render json: @skills
  end

  # GET /skills/1

  def show
    render json: @skill
  end

  # GET /skills/new


  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      render json: @skill, status: :created, location: api_v1_skill_url(@skill)
    else
      render json: @basic.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    if @skill.update(basic_params)
      render json: @skill
    else
      render json: @skill.errors, status: :unprocessable_entity
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :basic_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController
  before_action :set_basic, only: [:show, :edit, :update, :destroy]

  # GET /basics
  # GET /basics.json
  def index
    @basics = Basic.all
  end

  # GET /basics/1
  # GET /basics/1.json
  def show
  end

  # GET /basics/new
  def new
    @basic = Basic.new
  end

  # GET /basics/1/edit
  def edit
  end

  # POST /basics
  # POST /basics.json
  def create
    @basic = Basic.new(basic_params)

    respond_to do |format|
      if @basic.save
        format.html { redirect_to @basic, notice: 'Basic was successfully created.' }
        format.json { render :show, status: :created, location: @basic }
      else
        format.html { render :new }
        format.json { render json: @basic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basics/1
  # PATCH/PUT /basics/1.json
  def update
    respond_to do |format|
      if @basic.update(basic_params)
        format.html { redirect_to @basic, notice: 'Basic was successfully updated.' }
        format.json { render :show, status: :ok, location: @basic }
      else
        format.html { render :edit }
        format.json { render json: @basic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basics/1
  # DELETE /basics/1.json
  def destroy
    @basic.destroy
    respond_to do |format|
      format.html { redirect_to basics_url, notice: 'Basic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basic
      @basic = Basic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basic_params
      params.require(:basic).permit(:name, :age, :sex, :class, :race, :height)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basics_helper.rb
module BasicsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/basics/_form.html.erb
<%= form_with(model: basic, local: true) do |form| %>
  <% if basic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basic.errors.count, "error") %> prohibited this basic from being saved:</h2>

      <ul>
      <% basic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.text_field :class %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/basics/edit.html.erb
<h1>Editing Basic</h1>

<%= render 'form', basic: @basic %>

<%= link_to 'Show', @basic %> |
<%= link_to 'Back', basics_path %>

app/views/basics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Basics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Class</th>
      <th>Race</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basics.each do |basic| %>
      <tr>
        <td><%= basic.name %></td>
        <td><%= basic.age %></td>
        <td><%= basic.sex %></td>
        <td><%= basic.class %></td>
        <td><%= basic.race %></td>
        <td><%= basic.height %></td>
        <td><%= link_to 'Show', basic %></td>
        <td><%= link_to 'Edit', edit_basic_path(basic) %></td>
        <td><%= link_to 'Destroy', basic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basic', new_basic_path %>

app/views/basics/new.html.erb
<h1>New Basic</h1>

<%= render 'form', basic: @basic %>

<%= link_to 'Back', basics_path %>

app/views/basics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @basic.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @basic.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @basic.sex %>
</p>

<p>
  <strong>Class:</strong>
  <%= @basic.class %>
</p>

<p>
  <strong>Race:</strong>
  <%= @basic.race %>
</p>

<p>
  <strong>Height:</strong>
  <%= @basic.height %>
</p>

<%= link_to 'Edit', edit_basic_path(@basic) %> |
<%= link_to 'Back', basics_path %>

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, local: true) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CharacterApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength %>
  </div>

  <div class="field">
    <%= form.label :dexterity %>
    <%= form.number_field :dexterity %>
  </div>

  <div class="field">
    <%= form.label :constitution %>
    <%= form.number_field :constitution %>
  </div>

  <div class="field">
    <%= form.label :intelligence %>
    <%= form.number_field :intelligence %>
  </div>

  <div class="field">
    <%= form.label :wisdom %>
    <%= form.number_field :wisdom %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <%= form.number_field :charisma %>
  </div>

  <div class="field">
    <%= form.label :basic_id %>
    <%= form.text_field :basic_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Strength</th>
      <th>Dexterity</th>
      <th>Constitution</th>
      <th>Intelligence</th>
      <th>Wisdom</th>
      <th>Charisma</th>
      <th>Basic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.strength %></td>
        <td><%= skill.dexterity %></td>
        <td><%= skill.constitution %></td>
        <td><%= skill.intelligence %></td>
        <td><%= skill.wisdom %></td>
        <td><%= skill.charisma %></td>
        <td><%= skill.basic %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Strength:</strong>
  <%= @skill.strength %>
</p>

<p>
  <strong>Dexterity:</strong>
  <%= @skill.dexterity %>
</p>

<p>
  <strong>Constitution:</strong>
  <%= @skill.constitution %>
</p>

<p>
  <strong>Intelligence:</strong>
  <%= @skill.intelligence %>
</p>

<p>
  <strong>Wisdom:</strong>
  <%= @skill.wisdom %>
</p>

<p>
  <strong>Charisma:</strong>
  <%= @skill.charisma %>
</p>

<p>
  <strong>Basic:</strong>
  <%= @skill.basic %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>